version: '3.8'

services:
  drupal:
    build: .
    container_name: drupal-app
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - drupal-data:/var/www/html
    restart: always

  db:
    image: mariadb:10.9
    container_name: drupal-db
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  drupal-data:
  db-data:
